#!/usr/bin/env python3
import re
import sys
from pathlib import Path
from html import escape
import os


def short_location(location):
    location = location.strip()

    if location.startswith("<"):
        location = location[1:]

    return location.split(" line ")[0]


def parse_tlc_out(path: Path):
    text = path.read_text(errors="ignore")

    coverage_rows = []

    coverage_pattern = re.compile(
        r"(?P<location><[^>]+>|\d+:\d+-\d+:\d+).*?"
        r"(?P<distinct>\d+):(?P<count>\d+)"
    )

    for line in text.splitlines():
        match = coverage_pattern.search(line)
        if match:
            coverage_rows.append({
                "location": match.group("location"),
                "count": int(match.group("count")),
                "distinct": int(match.group("distinct")),
                "raw_line": line.strip(),
            })

    return coverage_rows


def write_html_report(path: Path, coverage_rows, graph_path=None):
    html = []
    html.append("<html><head><title>TLC Coverage Summary</title>")
    html.append("""
    <style>
      body { font-family: Arial, sans-serif; margin: 32px; }
      table { border-collapse: collapse; margin-bottom: 32px; width: 100%; }
      th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
      th { background: #f2f2f2; }
      code { background: #f6f6f6; padding: 2px 4px; }
    </style>
    """)
    html.append("</head><body>")
    html.append("<h1>TLC Coverage Summary</h1>")

    html.append("<h2>Coverage Rows</h2>")
    html.append(
        "<table><tr><th>Action/Location</th><th>Total</th><th>Distinct</th><th>Raw line</th></tr>"
    )

    for row in coverage_rows:
        location = escape(short_location(row["location"]))
        raw_line = escape(row["raw_line"])
        html.append(
            f"<tr><td><code>{location}</code></td>"
            f"<td>{row['count']}</td>"
            f"<td>{row['distinct']}</td>"
            f"<td><code>{raw_line}</code></td></tr>"
        )

    html.append("</table>")

    if graph_path is not None:
        relative_graph_path = os.path.relpath(graph_path, path.parent)

        html.append("<h2>State Graph</h2>")
        html.append(
            "<p>This graph shows the reachable state transitions generated by TLC.</p>"
        )
        html.append(
            f'<img src="{escape(relative_graph_path)}" '
            f'alt="TLC state graph" '
            f'style="max-width: 100%; border: 1px solid #ccc; border-radius: 8px;">'
        )

    html.append("</body></html>")
    path.write_text("\n".join(html))


def print_terminal_summary(input_path, report_path, graph_path, coverage_rows):
    print("\nTLC Coverage Summary")
    print("=" * 60)
    print(f"Input:  {input_path}")
    print(f"Report: {report_path}")

    if graph_path is not None:
        print(f"Graph:  {graph_path}")

    print("\nTop Coverage Rows")
    print("-" * 60)
    print(f"{'Action':35} {'Total':>10} {'Distinct':>10}")
    print("-" * 60)

    for row in coverage_rows:
        location = short_location(row.get("location", "unknown"))
        distinct = row.get("distinct", "")
        total = row.get("count", "")

        print(f"{location:35} {total:>10} {distinct:>10}")

    print("=" * 60)


def main():
    if len(sys.argv) not in [3, 4]:
        print(
            "Usage: python parse_tlc_out.py path/to/output.out "
            "path/to/report.html [path/to/state_graph.png]"
        )
        sys.exit(1)

    input_path = Path(sys.argv[1])
    report_path = Path(sys.argv[2])
    graph_path = Path(sys.argv[3]) if len(sys.argv) == 4 else None

    if not input_path.exists():
        print(f"File not found: {input_path}")
        sys.exit(1)

    if graph_path is not None and not graph_path.exists():
        print(f"Graph image not found: {graph_path}")
        sys.exit(1)

    report_path.parent.mkdir(parents=True, exist_ok=True)

    coverage_rows = parse_tlc_out(input_path)

    print_terminal_summary(input_path, report_path, graph_path, coverage_rows)
    write_html_report(report_path, coverage_rows, graph_path)

    print("Generated:")
    print(f"- {report_path}")


if __name__ == "__main__":
    main()